/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as WelcomeSplatRouteImport } from './routes/welcome/$'
import { Route as AuthenticatedSidebarRouteImport } from './routes/_authenticated/_sidebar'
import { Route as DebugAvatarsIndexRouteImport } from './routes/debug/avatars/index'
import { Route as AuthenticatedSidebarIndexRouteImport } from './routes/_authenticated/_sidebar/index'
import { Route as AuthenticatedSidebarChatsRouteRouteImport } from './routes/_authenticated/_sidebar/chats/route'
import { Route as AuthenticatedSidebarChatsIndexRouteImport } from './routes/_authenticated/_sidebar/chats/index'
import { Route as AuthenticatedSidebarCalendarIndexRouteImport } from './routes/_authenticated/_sidebar/calendar/index'
import { Route as AuthenticatedSidebarChatsIdRouteImport } from './routes/_authenticated/_sidebar/chats/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeSplatRoute = WelcomeSplatRouteImport.update({
  id: '/welcome/$',
  path: '/welcome/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSidebarRoute = AuthenticatedSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DebugAvatarsIndexRoute = DebugAvatarsIndexRouteImport.update({
  id: '/debug/avatars/',
  path: '/debug/avatars/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSidebarIndexRoute =
  AuthenticatedSidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarChatsRouteRoute =
  AuthenticatedSidebarChatsRouteRouteImport.update({
    id: '/chats',
    path: '/chats',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarChatsIndexRoute =
  AuthenticatedSidebarChatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSidebarChatsRouteRoute,
  } as any)
const AuthenticatedSidebarCalendarIndexRoute =
  AuthenticatedSidebarCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarChatsIdRoute =
  AuthenticatedSidebarChatsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSidebarChatsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedSidebarIndexRoute
  '/welcome/$': typeof WelcomeSplatRoute
  '/chats': typeof AuthenticatedSidebarChatsRouteRouteWithChildren
  '/debug/avatars/': typeof DebugAvatarsIndexRoute
  '/chats/$id': typeof AuthenticatedSidebarChatsIdRoute
  '/calendar/': typeof AuthenticatedSidebarCalendarIndexRoute
  '/chats/': typeof AuthenticatedSidebarChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedSidebarIndexRoute
  '/welcome/$': typeof WelcomeSplatRoute
  '/debug/avatars': typeof DebugAvatarsIndexRoute
  '/chats/$id': typeof AuthenticatedSidebarChatsIdRoute
  '/calendar': typeof AuthenticatedSidebarCalendarIndexRoute
  '/chats': typeof AuthenticatedSidebarChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_sidebar': typeof AuthenticatedSidebarRouteWithChildren
  '/welcome/$': typeof WelcomeSplatRoute
  '/_authenticated/_sidebar/chats': typeof AuthenticatedSidebarChatsRouteRouteWithChildren
  '/_authenticated/_sidebar/': typeof AuthenticatedSidebarIndexRoute
  '/debug/avatars/': typeof DebugAvatarsIndexRoute
  '/_authenticated/_sidebar/chats/$id': typeof AuthenticatedSidebarChatsIdRoute
  '/_authenticated/_sidebar/calendar/': typeof AuthenticatedSidebarCalendarIndexRoute
  '/_authenticated/_sidebar/chats/': typeof AuthenticatedSidebarChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome/$'
    | '/chats'
    | '/debug/avatars/'
    | '/chats/$id'
    | '/calendar/'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome/$'
    | '/debug/avatars'
    | '/chats/$id'
    | '/calendar'
    | '/chats'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_sidebar'
    | '/welcome/$'
    | '/_authenticated/_sidebar/chats'
    | '/_authenticated/_sidebar/'
    | '/debug/avatars/'
    | '/_authenticated/_sidebar/chats/$id'
    | '/_authenticated/_sidebar/calendar/'
    | '/_authenticated/_sidebar/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  WelcomeSplatRoute: typeof WelcomeSplatRoute
  DebugAvatarsIndexRoute: typeof DebugAvatarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/$': {
      id: '/welcome/$'
      path: '/welcome/$'
      fullPath: '/welcome/$'
      preLoaderRoute: typeof WelcomeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_sidebar': {
      id: '/_authenticated/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSidebarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/debug/avatars/': {
      id: '/debug/avatars/'
      path: '/debug/avatars'
      fullPath: '/debug/avatars/'
      preLoaderRoute: typeof DebugAvatarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_sidebar/': {
      id: '/_authenticated/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSidebarIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/chats': {
      id: '/_authenticated/_sidebar/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedSidebarChatsRouteRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/chats/': {
      id: '/_authenticated/_sidebar/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedSidebarChatsIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarChatsRouteRoute
    }
    '/_authenticated/_sidebar/calendar/': {
      id: '/_authenticated/_sidebar/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthenticatedSidebarCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/chats/$id': {
      id: '/_authenticated/_sidebar/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthenticatedSidebarChatsIdRouteImport
      parentRoute: typeof AuthenticatedSidebarChatsRouteRoute
    }
  }
}

interface AuthenticatedSidebarChatsRouteRouteChildren {
  AuthenticatedSidebarChatsIdRoute: typeof AuthenticatedSidebarChatsIdRoute
  AuthenticatedSidebarChatsIndexRoute: typeof AuthenticatedSidebarChatsIndexRoute
}

const AuthenticatedSidebarChatsRouteRouteChildren: AuthenticatedSidebarChatsRouteRouteChildren =
  {
    AuthenticatedSidebarChatsIdRoute: AuthenticatedSidebarChatsIdRoute,
    AuthenticatedSidebarChatsIndexRoute: AuthenticatedSidebarChatsIndexRoute,
  }

const AuthenticatedSidebarChatsRouteRouteWithChildren =
  AuthenticatedSidebarChatsRouteRoute._addFileChildren(
    AuthenticatedSidebarChatsRouteRouteChildren,
  )

interface AuthenticatedSidebarRouteChildren {
  AuthenticatedSidebarChatsRouteRoute: typeof AuthenticatedSidebarChatsRouteRouteWithChildren
  AuthenticatedSidebarIndexRoute: typeof AuthenticatedSidebarIndexRoute
  AuthenticatedSidebarCalendarIndexRoute: typeof AuthenticatedSidebarCalendarIndexRoute
}

const AuthenticatedSidebarRouteChildren: AuthenticatedSidebarRouteChildren = {
  AuthenticatedSidebarChatsRouteRoute:
    AuthenticatedSidebarChatsRouteRouteWithChildren,
  AuthenticatedSidebarIndexRoute: AuthenticatedSidebarIndexRoute,
  AuthenticatedSidebarCalendarIndexRoute:
    AuthenticatedSidebarCalendarIndexRoute,
}

const AuthenticatedSidebarRouteWithChildren =
  AuthenticatedSidebarRoute._addFileChildren(AuthenticatedSidebarRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSidebarRoute: typeof AuthenticatedSidebarRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSidebarRoute: AuthenticatedSidebarRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  WelcomeSplatRoute: WelcomeSplatRoute,
  DebugAvatarsIndexRoute: DebugAvatarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
