// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5200/' | (string & {})
}

export type CreateRoleRequest = {
  name: string
  hoist: boolean
  position: number | string
  permissions: PermissionSet
}

export type CreateUserRequest = {
  username: string
  email: string
  first_name?: null | string
  last_name?: null | string
}

export type GetEmailAvailabilityResponse = {
  email: string
  available: boolean
}

export type GetUsernameAvailabilityResponse = {
  username: string
  available: boolean
}

export type PermissionSet = unknown

export type RoleResponse = {
  id: string
  name: string
  hoist: boolean
  position: number | string
  permissions: PermissionSet
}

export type UserPublicResponse = {
  id: string
  username: string
  email: string
  first_name: null | string
  last_name: null | string
}

export type UserResponse = {
  id: string
  username: string
  email: string
  first_name: null | string
  last_name: null | string
  created_at: string
  updated_at: null | string
}

export type GetApiDebugEndpointsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/_debug/endpoints'
}

export type GetApiDebugEndpointsResponses = {
  /**
   * OK
   */
  200: unknown
}

export type GetCurrentUserData = {
  body?: never
  path?: never
  query?: never
  url: '/api/users/me'
}

export type GetCurrentUserResponses = {
  /**
   * OK
   */
  200: UserResponse
}

export type GetCurrentUserResponse =
  GetCurrentUserResponses[keyof GetCurrentUserResponses]

export type GetUserByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type GetUserByIdErrors = {
  /**
   * Not Found
   */
  404: unknown
}

export type GetUserByIdResponses = {
  /**
   * OK
   */
  200: UserPublicResponse
}

export type GetUserByIdResponse =
  GetUserByIdResponses[keyof GetUserByIdResponses]

export type OnboardUserData = {
  body: CreateUserRequest
  path?: never
  query?: never
  url: '/api/users/onboard'
}

export type OnboardUserErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Conflict
   */
  409: unknown
}

export type OnboardUserResponses = {
  /**
   * Created
   */
  201: UserResponse
}

export type OnboardUserResponse =
  OnboardUserResponses[keyof OnboardUserResponses]

export type UsernameAvailabilityData = {
  body?: never
  path?: never
  query: {
    username: string
  }
  url: '/api/users/username-availability'
}

export type UsernameAvailabilityResponses = {
  /**
   * OK
   */
  200: GetUsernameAvailabilityResponse
}

export type UsernameAvailabilityResponse =
  UsernameAvailabilityResponses[keyof UsernameAvailabilityResponses]

export type EmailAvailabilityData = {
  body?: never
  path?: never
  query: {
    email: string
  }
  url: '/api/users/email-availability'
}

export type EmailAvailabilityResponses = {
  /**
   * OK
   */
  200: GetEmailAvailabilityResponse
}

export type EmailAvailabilityResponse =
  EmailAvailabilityResponses[keyof EmailAvailabilityResponses]

export type GetRolesData = {
  body?: never
  path?: never
  query?: never
  url: '/api/roles'
}

export type GetRolesResponses = {
  /**
   * OK
   */
  200: Array<RoleResponse>
}

export type GetRolesResponse = GetRolesResponses[keyof GetRolesResponses]

export type CreateRoleData = {
  body: CreateRoleRequest
  path?: never
  query?: never
  url: '/api/roles'
}

export type CreateRoleResponses = {
  /**
   * Created
   */
  201: RoleResponse
}

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses]

export type GetRoleByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/roles/{id}'
}

export type GetRoleByIdErrors = {
  /**
   * Not Found
   */
  404: unknown
}

export type GetRoleByIdResponses = {
  /**
   * OK
   */
  200: RoleResponse
}

export type GetRoleByIdResponse =
  GetRoleByIdResponses[keyof GetRoleByIdResponses]

export type PostApiWebhooksClerkData = {
  body?: never
  path?: never
  query?: never
  url: '/api/webhooks/clerk'
}

export type PostApiWebhooksClerkResponses = {
  /**
   * OK
   */
  200: unknown
}
