/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthSidebarRouteImport } from './routes/_auth/_sidebar'
import { Route as AuthSidebarIndexRouteImport } from './routes/_auth/_sidebar/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSidebarRoute = AuthSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSidebarIndexRoute = AuthSidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSidebarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthSidebarIndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthSidebarIndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/_sidebar': typeof AuthSidebarRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_auth/_sidebar/': typeof AuthSidebarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/callback' | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/callback' | '/onboarding'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/_sidebar'
    | '/auth/callback'
    | '/onboarding/'
    | '/_auth/_sidebar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_sidebar': {
      id: '/_auth/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthSidebarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_sidebar/': {
      id: '/_auth/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthSidebarIndexRouteImport
      parentRoute: typeof AuthSidebarRoute
    }
  }
}

interface AuthSidebarRouteChildren {
  AuthSidebarIndexRoute: typeof AuthSidebarIndexRoute
}

const AuthSidebarRouteChildren: AuthSidebarRouteChildren = {
  AuthSidebarIndexRoute: AuthSidebarIndexRoute,
}

const AuthSidebarRouteWithChildren = AuthSidebarRoute._addFileChildren(
  AuthSidebarRouteChildren,
)

interface AuthRouteChildren {
  AuthSidebarRoute: typeof AuthSidebarRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSidebarRoute: AuthSidebarRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
