// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query'

import { client } from '../client.gen'
import {
  createRole,
  emailAvailability,
  getApiDebugEndpoints,
  getCurrentUser,
  getRoleById,
  getRoles,
  getUserById,
  onboardUser,
  type Options,
  postApiWebhooksClerk,
  usernameAvailability,
} from '../sdk.gen'
import type {
  CreateRoleData,
  CreateRoleResponse,
  EmailAvailabilityData,
  EmailAvailabilityResponse,
  GetApiDebugEndpointsData,
  GetCurrentUserData,
  GetCurrentUserResponse,
  GetRoleByIdData,
  GetRoleByIdResponse,
  GetRolesData,
  GetRolesResponse,
  GetUserByIdData,
  GetUserByIdResponse,
  OnboardUserData,
  OnboardUserResponse,
  PostApiWebhooksClerkData,
  UsernameAvailabilityData,
  UsernameAvailabilityResponse,
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getApiDebugEndpointsQueryKey = (
  options?: Options<GetApiDebugEndpointsData>,
) => createQueryKey('getApiDebugEndpoints', options)

export const getApiDebugEndpointsOptions = (
  options?: Options<GetApiDebugEndpointsData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiDebugEndpointsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDebugEndpoints({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDebugEndpointsQueryKey(options),
  })

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) =>
  createQueryKey('getCurrentUser', options)

/**
 * Get the currently authenticated user
 *
 * Returns the full profile of the user making the request. Requires a valid JWT token.
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) =>
  queryOptions<
    GetCurrentUserResponse,
    DefaultError,
    GetCurrentUserResponse,
    ReturnType<typeof getCurrentUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCurrentUserQueryKey(options),
  })

export const getUserByIdQueryKey = (options: Options<GetUserByIdData>) =>
  createQueryKey('getUserById', options)

/**
 * Get user by ID
 *
 * Retrieves a user profile by their unique identifier.
 */
export const getUserByIdOptions = (options: Options<GetUserByIdData>) =>
  queryOptions<
    GetUserByIdResponse,
    DefaultError,
    GetUserByIdResponse,
    ReturnType<typeof getUserByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserByIdQueryKey(options),
  })

/**
 * Onboard a new user
 *
 * Creates a new user account linked to an external identity (e.g. from Auth0, Firebase, etc.).
 * This endpoint is public and should be called after successful external authentication.
 */
export const onboardUserMutation = (
  options?: Partial<Options<OnboardUserData>>,
): UseMutationOptions<
  OnboardUserResponse,
  DefaultError,
  Options<OnboardUserData>
> => {
  const mutationOptions: UseMutationOptions<
    OnboardUserResponse,
    DefaultError,
    Options<OnboardUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await onboardUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const usernameAvailabilityQueryKey = (
  options: Options<UsernameAvailabilityData>,
) => createQueryKey('usernameAvailability', options)

/**
 * Check the availability of a username
 *
 * Checks whether a username is available or not, to be used with a frontend's input field
 */
export const usernameAvailabilityOptions = (
  options: Options<UsernameAvailabilityData>,
) =>
  queryOptions<
    UsernameAvailabilityResponse,
    DefaultError,
    UsernameAvailabilityResponse,
    ReturnType<typeof usernameAvailabilityQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usernameAvailability({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: usernameAvailabilityQueryKey(options),
  })

export const emailAvailabilityQueryKey = (
  options: Options<EmailAvailabilityData>,
) => createQueryKey('emailAvailability', options)

/**
 * Check the availability of an email
 *
 * Checks whether an email is available or not, to be used with a frontend's input field
 */
export const emailAvailabilityOptions = (
  options: Options<EmailAvailabilityData>,
) =>
  queryOptions<
    EmailAvailabilityResponse,
    DefaultError,
    EmailAvailabilityResponse,
    ReturnType<typeof emailAvailabilityQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await emailAvailability({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: emailAvailabilityQueryKey(options),
  })

export const getRolesQueryKey = (options?: Options<GetRolesData>) =>
  createQueryKey('getRoles', options)

/**
 * Get a list of available roles
 *
 * Returns a list of all available roles.
 */
export const getRolesOptions = (options?: Options<GetRolesData>) =>
  queryOptions<
    GetRolesResponse,
    DefaultError,
    GetRolesResponse,
    ReturnType<typeof getRolesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRolesQueryKey(options),
  })

/**
 * Create a role
 *
 * Tries to create a role, doing permission checks in the middle.
 */
export const createRoleMutation = (
  options?: Partial<Options<CreateRoleData>>,
): UseMutationOptions<
  CreateRoleResponse,
  DefaultError,
  Options<CreateRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRoleResponse,
    DefaultError,
    Options<CreateRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getRoleByIdQueryKey = (options: Options<GetRoleByIdData>) =>
  createQueryKey('getRoleById', options)

/**
 * Get a role by its ID
 *
 * Returns a role's details given its ID.
 */
export const getRoleByIdOptions = (options: Options<GetRoleByIdData>) =>
  queryOptions<
    GetRoleByIdResponse,
    DefaultError,
    GetRoleByIdResponse,
    ReturnType<typeof getRoleByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoleById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRoleByIdQueryKey(options),
  })

export const postApiWebhooksClerkMutation = (
  options?: Partial<Options<PostApiWebhooksClerkData>>,
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<PostApiWebhooksClerkData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<PostApiWebhooksClerkData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiWebhooksClerk({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
