// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  CreateRoleData,
  CreateRoleResponses,
  EmailAvailabilityData,
  EmailAvailabilityResponses,
  GetApiDebugEndpointsData,
  GetApiDebugEndpointsResponses,
  GetCurrentUserData,
  GetCurrentUserResponses,
  GetRoleByIdData,
  GetRoleByIdErrors,
  GetRoleByIdResponses,
  GetRolesData,
  GetRolesResponses,
  GetUserByIdData,
  GetUserByIdErrors,
  GetUserByIdResponses,
  OnboardUserData,
  OnboardUserErrors,
  OnboardUserResponses,
  PostApiWebhooksClerkData,
  PostApiWebhooksClerkResponses,
  UsernameAvailabilityData,
  UsernameAvailabilityResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const getApiDebugEndpoints = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiDebugEndpointsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiDebugEndpointsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/_debug/endpoints',
    ...options,
  })

/**
 * Get the currently authenticated user
 *
 * Returns the full profile of the user making the request. Requires a valid JWT token.
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetCurrentUserResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/me',
    ...options,
  })

/**
 * Get user by ID
 *
 * Retrieves a user profile by their unique identifier.
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUserByIdResponses,
    GetUserByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}',
    ...options,
  })

/**
 * Onboard a new user
 *
 * Creates a new user account linked to an external identity (e.g. from Auth0, Firebase, etc.).
 * This endpoint is public and should be called after successful external authentication.
 */
export const onboardUser = <ThrowOnError extends boolean = false>(
  options: Options<OnboardUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OnboardUserResponses,
    OnboardUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/onboard',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Check the availability of a username
 *
 * Checks whether a username is available or not, to be used with a frontend's input field
 */
export const usernameAvailability = <ThrowOnError extends boolean = false>(
  options: Options<UsernameAvailabilityData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    UsernameAvailabilityResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/username-availability',
    ...options,
  })

/**
 * Check the availability of an email
 *
 * Checks whether an email is available or not, to be used with a frontend's input field
 */
export const emailAvailability = <ThrowOnError extends boolean = false>(
  options: Options<EmailAvailabilityData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    EmailAvailabilityResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/email-availability',
    ...options,
  })

/**
 * Get a list of available roles
 *
 * Returns a list of all available roles.
 */
export const getRoles = <ThrowOnError extends boolean = false>(
  options?: Options<GetRolesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetRolesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles',
    ...options,
  })

/**
 * Create a role
 *
 * Tries to create a role, doing permission checks in the middle.
 */
export const createRole = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoleData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateRoleResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get a role by its ID
 *
 * Returns a role's details given its ID.
 */
export const getRoleById = <ThrowOnError extends boolean = false>(
  options: Options<GetRoleByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetRoleByIdResponses,
    GetRoleByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/roles/{id}',
    ...options,
  })

export const postApiWebhooksClerk = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiWebhooksClerkData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiWebhooksClerkResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/webhooks/clerk',
    ...options,
  })
